general.import = ["~/.config/alacritty/themes/themes/everforest_dark_hard.toml"]

[font]
size = 12.0

[window]
decorations = "None"
opacity = 0.75
blur = true

[font.normal]
family = "BigBlue TerminalPlus"
style = "Regular"

[font.bold]
family = "BigBlue TerminalPlus"
style = "Regular"

[font.bold_italic]
family = "BigBlue TerminalPlus"
style = "Regular"

[font.italic]
family = "BigBlue TerminalPlus"
style = "Italic"
